# File: kg/graph_store.py
from __future__ import annotations
from typing import Dict, Any, List, Optional, Protocol, Tuple


class GraphStore(Protocol):
    # ---------- upserts ----------
    def upsert_node(self, node_id: str, label: str, props: Dict[str, Any]) -> None: ...
    def upsert_edge(self, src_id: str, rel: str, dst_id: str, props: Optional[Dict[str, Any]] = None) -> None: ...

    # ---------- reads ----------
    def get_node(self, node_id: str) -> Optional[Dict[str, Any]]: ...
    def neighbors(self, node_id: str, rel: Optional[str] = None, direction: str = "out") -> List[str]: ...
    def edges(self, node_id: str, rel: Optional[str] = None, direction: str = "out") -> List[Tuple[str, str, str, Dict[str, Any]]]: ...
    def find_nodes(self, label: str, prop_key: str, prop_value: str) -> List[str]: ...

    # ---------- persistence ----------
    def save(self) -> None: ...
